import PDFDocument from "pdfkit";
import type {
  ReadinessReport,
  GapAnalysisReport,
  BoardSummaryReport,
  EvidencePackageReport,
} from "@blackfyre/shared";

// ---------------------------------------------------------------------------
// Color palette
// ---------------------------------------------------------------------------
const COLORS = {
  black: "#1A1A2E" as const,
  darkGray: "#3D3D5C" as const,
  mediumGray: "#6B6B8D" as const,
  lightGray: "#E8E8F0" as const,
  white: "#FFFFFF" as const,
  accent: "#6C63FF" as const,      // BLACKFYRE brand purple
  accentDark: "#4B44B2" as const,
  green: "#27AE60" as const,
  yellow: "#F2994A" as const,
  red: "#EB5757" as const,
  critical: "#C0392B" as const,
  high: "#E74C3C" as const,
  medium: "#F39C12" as const,
  low: "#3498DB" as const,
  info: "#95A5A6" as const,
};

// ---------------------------------------------------------------------------
// Helpers
// ---------------------------------------------------------------------------

function scoreColor(score: number): string {
  if (score > 80) return COLORS.green;
  if (score >= 60) return COLORS.yellow;
  return COLORS.red;
}

function statusColor(status: string): string {
  switch (status) {
    case "pass":
      return COLORS.green;
    case "fail":
      return COLORS.red;
    case "partial":
      return COLORS.yellow;
    default:
      return COLORS.mediumGray;
  }
}

function severityColor(severity: string): string {
  switch (severity) {
    case "critical":
      return COLORS.critical;
    case "high":
      return COLORS.high;
    case "medium":
      return COLORS.medium;
    case "low":
      return COLORS.low;
    case "info":
      return COLORS.info;
    default:
      return COLORS.mediumGray;
  }
}

function formatDate(iso: string): string {
  const d = new Date(iso);
  return d.toLocaleDateString("en-US", {
    year: "numeric",
    month: "long",
    day: "numeric",
    hour: "2-digit",
    minute: "2-digit",
  });
}

/** Collect all chunks from a PDFDocument into a Buffer. */
function docToBuffer(doc: InstanceType<typeof PDFDocument>): Promise<Buffer> {
  return new Promise((resolve, reject) => {
    const chunks: Uint8Array[] = [];
    doc.on("data", (chunk: Uint8Array) => chunks.push(chunk));
    doc.on("end", () => resolve(Buffer.concat(chunks)));
    doc.on("error", reject);
  });
}

// ---------------------------------------------------------------------------
// Shared layout primitives
// ---------------------------------------------------------------------------

function renderHeader(doc: InstanceType<typeof PDFDocument>): void {
  // Purple header band
  doc
    .rect(0, 0, doc.page.width, 80)
    .fill(COLORS.accent);

  doc
    .font("Helvetica-Bold")
    .fontSize(24)
    .fillColor(COLORS.white)
    .text("BLACKFYRE", 50, 25, { continued: true })
    .font("Helvetica")
    .fontSize(12)
    .text("  Security Platform", { baseline: "alphabetic" });

  doc.moveDown(2);
}

function renderTitle(doc: InstanceType<typeof PDFDocument>, title: string, subtitle: string): void {
  const y = 100;
  doc
    .font("Helvetica-Bold")
    .fontSize(20)
    .fillColor(COLORS.black)
    .text(title, 50, y);

  doc
    .font("Helvetica")
    .fontSize(11)
    .fillColor(COLORS.mediumGray)
    .text(subtitle, 50, y + 28);

  // Thin separator line
  doc
    .moveTo(50, y + 50)
    .lineTo(doc.page.width - 50, y + 50)
    .strokeColor(COLORS.lightGray)
    .lineWidth(1)
    .stroke();

  doc.y = y + 60;
}

function renderFooter(doc: InstanceType<typeof PDFDocument>): void {
  const pages = doc.bufferedPageRange();
  for (let i = pages.start; i < pages.start + pages.count; i++) {
    doc.switchToPage(i);

    // Footer line
    const footerY = doc.page.height - 50;
    doc
      .moveTo(50, footerY)
      .lineTo(doc.page.width - 50, footerY)
      .strokeColor(COLORS.lightGray)
      .lineWidth(0.5)
      .stroke();

    doc
      .font("Helvetica")
      .fontSize(8)
      .fillColor(COLORS.mediumGray)
      .text(
        "Generated by BLACKFYRE Security Platform",
        50,
        footerY + 8,
        { width: doc.page.width - 100, align: "left" },
      );

    doc
      .text(
        `Page ${i + 1} of ${pages.count}`,
        50,
        footerY + 8,
        { width: doc.page.width - 100, align: "right" },
      );
  }
}

function renderSectionHeader(doc: InstanceType<typeof PDFDocument>, text: string): void {
  ensureSpace(doc, 40);
  doc
    .font("Helvetica-Bold")
    .fontSize(14)
    .fillColor(COLORS.accentDark)
    .text(text, 50);

  doc
    .moveTo(50, doc.y + 4)
    .lineTo(doc.page.width - 50, doc.y + 4)
    .strokeColor(COLORS.accent)
    .lineWidth(0.5)
    .stroke();

  doc.y += 12;
}

/** Make sure there is enough vertical space; add page if not. */
function ensureSpace(doc: InstanceType<typeof PDFDocument>, needed: number): void {
  if (doc.y + needed > doc.page.height - 70) {
    doc.addPage();
    doc.y = 50;
  }
}

// ---------------------------------------------------------------------------
// Table helpers
// ---------------------------------------------------------------------------

interface TableColumn {
  header: string;
  width: number;
  align?: "left" | "center" | "right";
}

function renderTableHeader(
  doc: InstanceType<typeof PDFDocument>,
  columns: TableColumn[],
  x: number,
): void {
  const y = doc.y;
  // Header background
  const totalWidth = columns.reduce((sum, c) => sum + c.width, 0);
  doc.rect(x, y, totalWidth, 20).fill(COLORS.accent);

  let cx = x;
  for (const col of columns) {
    doc
      .font("Helvetica-Bold")
      .fontSize(9)
      .fillColor(COLORS.white)
      .text(col.header, cx + 4, y + 5, {
        width: col.width - 8,
        align: col.align ?? "left",
      });
    cx += col.width;
  }
  doc.y = y + 22;
}

function renderTableRow(
  doc: InstanceType<typeof PDFDocument>,
  columns: TableColumn[],
  values: string[],
  x: number,
  options?: { rowColor?: string; zebra?: boolean; rowIndex?: number },
): void {
  ensureSpace(doc, 22);
  const y = doc.y;

  // Zebra striping
  if (options?.zebra && (options.rowIndex ?? 0) % 2 === 0) {
    const totalWidth = columns.reduce((sum, c) => sum + c.width, 0);
    doc.rect(x, y, totalWidth, 18).fill("#F5F5FA");
  }

  let cx = x;
  for (let i = 0; i < columns.length; i++) {
    const col = columns[i]!;
    doc
      .font("Helvetica")
      .fontSize(9)
      .fillColor(options?.rowColor ?? COLORS.darkGray)
      .text(values[i] ?? "", cx + 4, y + 4, {
        width: col.width - 8,
        align: col.align ?? "left",
      });
    cx += col.width;
  }
  doc.y = y + 20;
}

// ---------------------------------------------------------------------------
// Score badge (large circular-ish display)
// ---------------------------------------------------------------------------

function renderScoreBadge(
  doc: InstanceType<typeof PDFDocument>,
  score: number,
  x: number,
  y: number,
): void {
  const color = scoreColor(score);
  const radius = 35;

  // Circle background
  doc.circle(x, y, radius).fill(color);

  // Score text
  doc
    .font("Helvetica-Bold")
    .fontSize(22)
    .fillColor(COLORS.white)
    .text(`${score}`, x - radius, y - 12, {
      width: radius * 2,
      align: "center",
    });

  // Label below
  doc
    .font("Helvetica")
    .fontSize(8)
    .fillColor(color)
    .text("Overall Score", x - radius, y + radius + 6, {
      width: radius * 2,
      align: "center",
    });
}

// ---------------------------------------------------------------------------
// Bar chart (simple horizontal bars)
// ---------------------------------------------------------------------------

function renderHorizontalBar(
  doc: InstanceType<typeof PDFDocument>,
  label: string,
  value: number,
  maxValue: number,
  barColor: string,
  x: number,
  width: number,
): void {
  ensureSpace(doc, 24);
  const y = doc.y;
  const barHeight = 14;
  const labelWidth = 70;
  const barMaxWidth = width - labelWidth - 50;
  const barWidth = maxValue > 0 ? (value / maxValue) * barMaxWidth : 0;

  // Label
  doc
    .font("Helvetica")
    .fontSize(9)
    .fillColor(COLORS.darkGray)
    .text(label, x, y + 2, { width: labelWidth });

  // Background track
  doc
    .rect(x + labelWidth, y, barMaxWidth, barHeight)
    .fill(COLORS.lightGray);

  // Filled bar
  if (barWidth > 0) {
    doc
      .rect(x + labelWidth, y, barWidth, barHeight)
      .fill(barColor);
  }

  // Value text
  doc
    .font("Helvetica-Bold")
    .fontSize(9)
    .fillColor(COLORS.darkGray)
    .text(`${value}`, x + labelWidth + barMaxWidth + 6, y + 2);

  doc.y = y + barHeight + 6;
}

// ---------------------------------------------------------------------------
// Stat card (compact key-value box)
// ---------------------------------------------------------------------------

function renderStatCard(
  doc: InstanceType<typeof PDFDocument>,
  label: string,
  value: string,
  x: number,
  y: number,
  width: number,
  height: number,
  color?: string,
): void {
  // Card background
  doc
    .roundedRect(x, y, width, height, 4)
    .fill("#F7F7FC");

  // Value
  doc
    .font("Helvetica-Bold")
    .fontSize(18)
    .fillColor(color ?? COLORS.accent)
    .text(value, x + 8, y + 10, { width: width - 16, align: "center" });

  // Label
  doc
    .font("Helvetica")
    .fontSize(8)
    .fillColor(COLORS.mediumGray)
    .text(label, x + 8, y + 34, { width: width - 16, align: "center" });
}

// ===========================================================================
// PdfRenderer
// ===========================================================================

export class PdfRenderer {
  // -----------------------------------------------------------------------
  // Readiness Report
  // -----------------------------------------------------------------------
  async renderReadinessReport(data: ReadinessReport): Promise<Buffer> {
    const doc = new PDFDocument({
      size: "A4",
      margins: { top: 50, bottom: 70, left: 50, right: 50 },
      bufferPages: true,
    });
    const bufferPromise = docToBuffer(doc);

    renderHeader(doc);
    renderTitle(
      doc,
      `${data.framework} Compliance Readiness Report`,
      `Generated ${formatDate(data.generatedAt)}`,
    );

    // --- Overall score badge + control summary cards ---
    const badgeX = 100;
    const badgeY = doc.y + 40;
    renderScoreBadge(doc, data.overallScore, badgeX, badgeY);

    const cardsX = 200;
    const cardW = 90;
    const cardH = 55;
    const cardGap = 10;

    renderStatCard(doc, "Total Controls", `${data.totalControls}`, cardsX, badgeY - 28, cardW, cardH, COLORS.accent);
    renderStatCard(doc, "Passing", `${data.passCount}`, cardsX + cardW + cardGap, badgeY - 28, cardW, cardH, COLORS.green);
    renderStatCard(doc, "Failing", `${data.failCount}`, cardsX + (cardW + cardGap) * 2, badgeY - 28, cardW, cardH, COLORS.red);
    renderStatCard(doc, "Partial", `${data.partialCount}`, cardsX + (cardW + cardGap) * 3, badgeY - 28, cardW, cardH, COLORS.yellow);

    doc.y = badgeY + 60;

    // --- Top Failing Controls Table ---
    if (data.topFailingControls.length > 0) {
      renderSectionHeader(doc, "Top Failing Controls");
      doc.y += 4;

      const tableCols: TableColumn[] = [
        { header: "#", width: 30, align: "center" },
        { header: "Control ID", width: 110 },
        { header: "Control Name", width: 220 },
        { header: "Category", width: 130 },
      ];

      renderTableHeader(doc, tableCols, 50);
      data.topFailingControls.forEach((ctrl, idx) => {
        renderTableRow(doc, tableCols, [
          `${idx + 1}`,
          ctrl.controlId,
          ctrl.controlName,
          ctrl.category,
        ], 50, { zebra: true, rowIndex: idx });
      });
    }

    doc.y += 16;

    // --- Findings by Severity ---
    renderSectionHeader(doc, "Findings by Severity");
    doc.y += 4;

    const severities = Object.entries(data.findingsBySeverity);
    const maxSev = Math.max(...severities.map(([, v]) => v), 1);

    for (const [severity, count] of severities) {
      renderHorizontalBar(
        doc,
        severity.charAt(0).toUpperCase() + severity.slice(1),
        count,
        maxSev,
        severityColor(severity),
        50,
        doc.page.width - 100,
      );
    }

    renderFooter(doc);
    doc.end();
    return bufferPromise;
  }

  // -----------------------------------------------------------------------
  // Gap Analysis Report
  // -----------------------------------------------------------------------
  async renderGapAnalysis(data: GapAnalysisReport): Promise<Buffer> {
    const doc = new PDFDocument({
      size: "A4",
      margins: { top: 50, bottom: 70, left: 50, right: 50 },
      bufferPages: true,
    });
    const bufferPromise = docToBuffer(doc);

    renderHeader(doc);
    renderTitle(
      doc,
      `${data.framework} Gap Analysis Report`,
      `Generated ${formatDate(data.generatedAt)}`,
    );

    // Total gaps stat
    const badgeY = doc.y + 10;
    renderStatCard(doc, "Total Gaps", `${data.totalGaps}`, 50, badgeY, 120, 55, COLORS.red);

    renderStatCard(
      doc,
      "Categories Affected",
      `${data.gaps.length}`,
      185,
      badgeY,
      120,
      55,
      COLORS.yellow,
    );

    doc.y = badgeY + 75;

    // --- Gaps by Category ---
    for (const group of data.gaps) {
      renderSectionHeader(doc, group.category);
      doc.y += 4;

      const tableCols: TableColumn[] = [
        { header: "Control ID", width: 110 },
        { header: "Control Name", width: 230 },
        { header: "Status", width: 70, align: "center" },
        { header: "Findings", width: 70, align: "center" },
      ];

      renderTableHeader(doc, tableCols, 50);
      group.controls.forEach((ctrl, idx) => {
        renderTableRow(
          doc,
          tableCols,
          [ctrl.controlId, ctrl.controlName, ctrl.status.toUpperCase(), `${ctrl.findingCount}`],
          50,
          { zebra: true, rowIndex: idx, rowColor: statusColor(ctrl.status) },
        );
      });

      doc.y += 10;
    }

    renderFooter(doc);
    doc.end();
    return bufferPromise;
  }

  // -----------------------------------------------------------------------
  // Board Summary Report
  // -----------------------------------------------------------------------
  async renderBoardSummary(data: BoardSummaryReport): Promise<Buffer> {
    const doc = new PDFDocument({
      size: "A4",
      margins: { top: 50, bottom: 70, left: 50, right: 50 },
      bufferPages: true,
    });
    const bufferPromise = docToBuffer(doc);

    renderHeader(doc);
    renderTitle(
      doc,
      "Executive Board Summary",
      `Generated ${formatDate(data.generatedAt)}`,
    );

    // --- Key metrics row ---
    const metricsY = doc.y + 10;
    const mw = 110;
    const mh = 55;
    const mg = 12;

    renderStatCard(doc, "Open Findings", `${data.totalOpenFindings}`, 50, metricsY, mw, mh, COLORS.yellow);
    renderStatCard(doc, "Critical", `${data.criticalFindings}`, 50 + mw + mg, metricsY, mw, mh, COLORS.red);
    renderStatCard(doc, "Remediation", `${data.remediationProgress}%`, 50 + (mw + mg) * 2, metricsY, mw, mh, COLORS.green);
    renderStatCard(doc, "Recent Scans", `${data.recentScanCount}`, 50 + (mw + mg) * 3, metricsY, mw, mh, COLORS.accent);

    doc.y = metricsY + mh + 30;

    // --- Framework Scores Table ---
    renderSectionHeader(doc, "Framework Compliance Scores");
    doc.y += 4;

    const tableCols: TableColumn[] = [
      { header: "Framework", width: 250 },
      { header: "Score", width: 80, align: "center" },
      { header: "Status", width: 150, align: "center" },
    ];

    renderTableHeader(doc, tableCols, 50);
    data.frameworkScores.forEach((fs, idx) => {
      const statusLabel = fs.score > 80 ? "COMPLIANT" : fs.score >= 60 ? "AT RISK" : "NON-COMPLIANT";
      renderTableRow(
        doc,
        tableCols,
        [fs.framework, `${fs.score}%`, statusLabel],
        50,
        { zebra: true, rowIndex: idx, rowColor: scoreColor(fs.score) },
      );
    });

    doc.y += 16;

    // --- Framework score bars ---
    renderSectionHeader(doc, "Score Overview");
    doc.y += 4;

    const maxScore = 100;
    for (const fs of data.frameworkScores) {
      renderHorizontalBar(
        doc,
        fs.framework,
        fs.score,
        maxScore,
        scoreColor(fs.score),
        50,
        doc.page.width - 100,
      );
    }

    renderFooter(doc);
    doc.end();
    return bufferPromise;
  }

  // -----------------------------------------------------------------------
  // Evidence Package Report
  // -----------------------------------------------------------------------
  async renderEvidencePackage(data: EvidencePackageReport): Promise<Buffer> {
    const doc = new PDFDocument({
      size: "A4",
      margins: { top: 50, bottom: 70, left: 50, right: 50 },
      bufferPages: true,
    });
    const bufferPromise = docToBuffer(doc);

    renderHeader(doc);
    renderTitle(
      doc,
      `${data.framework} Evidence Package`,
      `Generated ${formatDate(data.generatedAt)}`,
    );

    // Summary stat
    const totalEvidence = data.controls.reduce((s, c) => s + c.evidenceItems.length, 0);
    const sy = doc.y + 10;
    renderStatCard(doc, "Controls", `${data.controls.length}`, 50, sy, 110, 55, COLORS.accent);
    renderStatCard(doc, "Evidence Items", `${totalEvidence}`, 175, sy, 120, 55, COLORS.green);
    doc.y = sy + 80;

    // --- Control-by-control listing ---
    for (const ctrl of data.controls) {
      ensureSpace(doc, 60);

      // Control header row
      doc
        .roundedRect(50, doc.y, doc.page.width - 100, 28, 3)
        .fill(COLORS.lightGray);

      doc
        .font("Helvetica-Bold")
        .fontSize(10)
        .fillColor(COLORS.black)
        .text(`${ctrl.controlId}  `, 58, doc.y + 7, { continued: true })
        .font("Helvetica")
        .text(ctrl.controlName, { continued: true })
        .text("");

      // Status badge (inline)
      const stColor = statusColor(ctrl.status);
      const statusText = ctrl.status.toUpperCase();
      const badgeX = doc.page.width - 130;
      doc
        .roundedRect(badgeX, doc.y - 21, 65, 18, 3)
        .fill(stColor);
      doc
        .font("Helvetica-Bold")
        .fontSize(8)
        .fillColor(COLORS.white)
        .text(statusText, badgeX + 4, doc.y - 18, { width: 57, align: "center" });

      doc.y += 8;

      // Evidence items
      if (ctrl.evidenceItems.length === 0) {
        doc
          .font("Helvetica-Oblique")
          .fontSize(9)
          .fillColor(COLORS.mediumGray)
          .text("No evidence collected for this control.", 70);
        doc.y += 6;
      } else {
        const evCols: TableColumn[] = [
          { header: "Type", width: 130 },
          { header: "Collected At", width: 200 },
          { header: "Collected By", width: 150 },
        ];
        renderTableHeader(doc, evCols, 60);

        ctrl.evidenceItems.forEach((ev, idx) => {
          renderTableRow(
            doc,
            evCols,
            [ev.type, formatDate(ev.collectedAt), ev.collectedBy],
            60,
            { zebra: true, rowIndex: idx },
          );
        });
      }

      doc.y += 10;
    }

    renderFooter(doc);
    doc.end();
    return bufferPromise;
  }
}
