"use client";

import { useState } from "react";
import Link from "next/link";
import HaloNav from "@/components/halo/HaloNav";
import HaloFooter from "@/components/halo/HaloFooter";
import HaloCTA from "@/components/halo/HaloCTA";
import HaloReveal from "@/components/halo/HaloReveal";
import ContactForm from "@/components/ContactForm";

interface ServiceItem {
  id: string;
  name: string;
  category: "security" | "identity" | "cloud" | "ai" | "development";
  description: string;
  tags: string[];
  features: string[];
  shipTime: string;
  iconType: "shield" | "vapt" | "compliance" | "endpoint" | "arch" | "cloud" | "cloud-managed" | "infra" | "hosting" | "ai" | "ethics" | "iam" | "mdm" | "gworkspace" | "itsm" | "web" | "mobile";
}

const SERVICES: readonly ServiceItem[] = [
  {
    id: "vciso",
    name: "vCISO (Virtual CISO)",
    category: "security",
    description: "Fractional security leadership, risk management, and board-level reporting on demand. We help establish security policies, manage incidents, and represent security posture to stakeholders and auditors.",
    tags: ["Security Strategy", "Risk Assessment", "Audit Preparation", "Board Reporting"],
    features: ["Custom security policy design", "Incident response planning", "Third-party risk management", "Continuous advisory meetings"],
    shipTime: "Immediate onboarding",
    iconType: "shield",
  },
  {
    id: "vapt",
    name: "VAPT / Penetration Testing",
    category: "security",
    description: "Find critical vulnerabilities before malicious actors do. We perform high-depth manual and automated testing across web applications, APIs, mobile apps, network segments, and cloud infrastructure.",
    tags: ["Penetration Testing", "API Security", "Red Teaming", "OWASP Top 10", "CERT-In Scoping"],
    features: ["High-depth manual vulnerability testing", "Zero-day exploration", "Same-day escalation for critical findings", "Detailed audit-ready reports and free re-testing"],
    shipTime: "Engage in 48 hours",
    iconType: "vapt",
  },
  {
    id: "compliance",
    name: "Audit & Compliance Advisory",
    category: "security",
    description: "End-to-end guidance from readiness assessment through final certification audits. We translate complex frameworks into clear engineering tasks and gather required evidence autonomously.",
    tags: ["SOC 2 Type I/II", "ISO 27001", "HIPAA", "GDPR", "PCI-DSS v4.0", "DPDPA"],
    features: ["Gap analysis and remediation plans", "Autogenerated compliance controls mapping", "Evidence collection automation", "Liaison with external auditors"],
    shipTime: "Launch same-week",
    iconType: "compliance",
  },
  {
    id: "sec-architecture",
    name: "Security Architecture Design",
    category: "security",
    description: "Build defensible network topologies and zero-trust systems. We design, configure, and automate security telemetry using modern SIEM/SOAR platforms without reseller lock-in.",
    tags: ["Zero Trust", "SIEM/SOAR", "Security Automation", "Data Loss Prevention (DLP)"],
    features: ["Zero-trust network scoping", "Datadog, Splunk, or Elastic configuration", "Automated alert playbooks", "IAM policy hardening"],
    shipTime: "2-4 week projects",
    iconType: "arch",
  },
  {
    id: "endpoint-security",
    name: "Endpoint Security & EDR",
    category: "security",
    description: "Deploy and manage advanced endpoint protection (EDR/XDR) and next-generation firewalls. Vendor-neutral recommendations matching your stack and budget.",
    tags: ["EDR/XDR", "Defender Endpoint", "Threat Detection", "OS Hardening", "CrowdStrike"],
    features: ["EDR agent deployment & monitoring", "Custom detection rule setups", "Threat containment strategies", "Vulnerability patching"],
    shipTime: "Day-one integration",
    iconType: "endpoint",
  },
  {
    id: "cloud-services",
    name: "Cloud Architecture & FinOps",
    category: "cloud",
    description: "Design and implement secure, scalable cloud infrastructure across AWS, Azure, and GCP. Hardened topologies that hold up under strict audit constraints.",
    tags: ["AWS", "Azure", "GCP", "Multi-Cloud", "FinOps", "Cost Optimization"],
    features: ["Zero-trust network architecture", "IAM role Least-Privilege optimization", "Cloud Cost & FinOps audits", "Terraform & IaC setup"],
    shipTime: "Launch same-week",
    iconType: "cloud",
  },
  {
    id: "cloud-managed",
    name: "Cloud Managed Services",
    category: "cloud",
    description: "Continuous monitoring, active incident containment, and compliance automation. We manage your cloud operations so your team can focus on shipping product.",
    tags: ["Continuous Monitoring", "Incident Response", "Compliance Automation", "Automated Backups"],
    features: ["24/7 incident response support", "Auto-remediation drift policies", "Log aggregation & analysis", "Backup & disaster recovery runs"],
    shipTime: "Immediate coverage",
    iconType: "cloud-managed",
  },
  {
    id: "infra-services",
    name: "Infrastructure Services",
    category: "cloud",
    description: "Modernize your baseline computing, database, and storage architecture. Connect hybrid or on-premise infrastructure securely to your cloud tenants.",
    tags: ["Network Topologies", "Secure Servers", "Storage Hardening", "Hybrid Routing"],
    features: ["IPS/IDS firewall configuration", "Database clustering & replication", "Virtual private network links", "On-premise active scanning"],
    shipTime: "2-4 week projects",
    iconType: "infra",
  },
  {
    id: "private-hosting",
    name: "Private Cloud Hosting",
    category: "cloud",
    description: "Dedicated, completely isolated hosting environments matching regulatory compliance guidelines. Fully managed patching with strict uptime SLAs.",
    tags: ["Dedicated Infrastructure", "High Availability", "Uptime SLA", "Managed Patching"],
    features: ["99.95% availability SLA guarantees", "Isolated compute & database clusters", "Automated system patching", "Regulatory audits mapping"],
    shipTime: "4-8 weeks setup",
    iconType: "hosting",
  },
  {
    id: "ai-security",
    name: "AI & LLM Security",
    category: "ai",
    description: "Protect your AI/ML models, RAG pipelines, and training pipelines against adversarial attacks. We evaluate prompt injection vulnerabilities and audit data retrieval boundaries.",
    tags: ["LLM Threat Assessment", "Prompt Injection Defense", "RAG Pipeline Auditing", "AI Red Teaming"],
    features: ["Lakera Guard & Prompt Armor setup", "Adversarial prompt simulation", "PII filtering configurations", "Model supply chain auditing"],
    shipTime: "1-2 week sprints",
    iconType: "ai",
  },
  {
    id: "ai-compliance",
    name: "AI Compliance & Ethics",
    category: "ai",
    description: "Prepare your organization for the EU AI Act, NIST AI RMF, and algorithmic transparency mandates. We establish AI governance boards and run algorithmic bias assessments.",
    tags: ["EU AI Act", "NIST AI RMF", "Algorithmic Audits", "Ethics Frameworks"],
    features: ["Risk categorization assessments", "Bias measurement & reporting", "Data lineage documentation", "Governance workflow templates"],
    shipTime: "Advisory retinue",
    iconType: "ethics",
  },
  {
    id: "iam",
    name: "Identity & Access Management (IAM)",
    category: "identity",
    description: "Centralize identity directory services, enforce multi-factor authentication (MFA) and single sign-on (SSO), and automate employee onboarding/offboarding workflows.",
    tags: ["Okta", "Entra ID", "SSO/MFA", "Lifecycle Management", "Least Privilege"],
    features: ["IdP federation & migration", "Strict conditional access policies", "Automated access requests", "Regular entitlement reviews"],
    shipTime: "1-2 week configuration",
    iconType: "iam",
  },
  {
    id: "mdm",
    name: "Endpoint Security & MDM",
    category: "identity",
    description: "Deploy and manage Mobile Device Management (MDM) agents to enforce disk encryption, firewall status, security updates, and remote locks across macOS, Windows, and mobile devices.",
    tags: ["Jamf Pro", "Kandji", "JumpCloud MDM", "Zero-Touch Enrollment"],
    features: ["Zero-touch employee enrollment setups", "Security baselines enforcement (FileVault, BitLocker)", "Endpoint detection & response (EDR) agents", "Software patch automation"],
    shipTime: "Immediate deployment",
    iconType: "mdm",
  },
  {
    id: "gworkspace",
    name: "Google Workspace Hardening",
    category: "identity",
    description: "Deploy, secure, and manage Google Workspace settings to prevent data leakage, configure security keys, and manage file sharing controls.",
    tags: ["Workspace Security", "DLP Rules", "Gmail Spam Filters", "Security Keys"],
    features: ["Workspace security assessment", "External file sharing restriction", "OAuth application whitelisting", "DKIM/SPF/DMARC implementation"],
    shipTime: "3-5 days configuration",
    iconType: "gworkspace",
  },
  {
    id: "itsm",
    name: "ITSM & Service Desk Setup",
    category: "identity",
    description: "Implement service desk software (Freshservice, Jira Service Management) to establish clean IT service request management, asset tracking, and SLA monitoring.",
    tags: ["Freshservice", "Jira Service Desk", "SLA Configuration", "Asset Management"],
    features: ["Ticketing system setup", "Auto-routing escalation rules", "ITIL asset tracking integrations", "SLA violation triggers"],
    shipTime: "1-2 week implementation",
    iconType: "itsm",
  },
  {
    id: "web-dev",
    name: "Web Application & SaaS Development",
    category: "development",
    description: "End-to-end design, frontend rendering, API architecture, database schema, and deployment. We deliver clean, lightning-fast web assets hosted on scalable cloud-native architectures.",
    tags: ["Next.js", "Fastify", "Drizzle ORM", "Tailwind CSS", "Serverless SST"],
    features: ["Fully custom SEO-optimized frontends", "Highly secure API structures", "Database migrations & row-level security", "Git-centric automated pipelines"],
    shipTime: "4-8 weeks delivery",
    iconType: "web",
  },
  {
    id: "mobile-dev",
    name: "Mobile App Development",
    category: "development",
    description: "Create fluid, native, or cross-platform applications for iOS and Android. We manage store listings, signing keys, and secure cloud backups.",
    tags: ["iOS", "Android", "Flutter", "React Native", "App Store Scoping"],
    features: ["Native iOS/Android build craft", "Biometric login & keychain security", "Push notification backend setup", "App store submission advisory"],
    shipTime: "6-10 weeks delivery",
    iconType: "mobile",
  },
];

interface FAQItem {
  q: string;
  a: string;
}

const FAQS: readonly FAQItem[] = [
  {
    q: "How fast can we achieve compliance audit readiness?",
    a: "Our compliance advisory combined with the Blackfyre automated scanners allows teams to build evidence in weeks rather than months. Initial cloud infrastructure scanner reports are generated within 10 minutes of connection, highlighting critical gaps immediately.",
  },
  {
    q: "Are the penetration tests (VAPT) performed by certified experts?",
    a: "Yes. Every assessment is scoped, executed, and signed off by senior security practitioners holding credentials like OSCP, CISSP, and AWS Security Specialty. We support OWASP frameworks, CERT-In compliance mandates, and RBI cyber-security checklists.",
  },
  {
    q: "How do your automated scanner agents access our cloud infrastructure?",
    a: "We use read-only cross-account IAM role delegation (using AWS STS or Azure App Registrations). We do not require or support write-access keys, keeping your production assets completely insulated. All scanner sandboxes conform strictly to Least Privilege guidelines.",
  },
  {
    q: "Do you build custom SaaS features or just security dashboards?",
    a: "We are active practitioners in software engineering as well as security. We design and deliver custom web portals, Next.js applications, serverless infrastructures, and native iOS/Android applications, handing over complete ownership of source codes and keys.",
  },
  {
    q: "What engagement shape fits a growing startup best?",
    a: "Most startups begin with a project-based VAPT or Compliance Advisory sprint, then transition to a flexible Monthly Retainer for fractional vCISO support and recurring automated scan checks.",
  },
];

export default function PortfolioPage() {
  const [activeCategory, setActiveCategory] = useState<string>("all");
  const [searchQuery, setSearchQuery] = useState("");
  const [faqOpenIndex, setFaqOpenIndex] = useState<number | null>(null);

  const filteredServices = SERVICES.filter((svc) => {
    if (activeCategory !== "all" && svc.category !== activeCategory) {
      return false;
    }
    if (searchQuery.trim() !== "") {
      const q = searchQuery.toLowerCase();
      const matchName = svc.name.toLowerCase().includes(q);
      const matchTags = svc.tags.some((t) => t.toLowerCase().includes(q));
      return matchName || matchTags;
    }
    return true;
  });

  const toggleFaq = (index: number) => {
    setFaqOpenIndex(faqOpenIndex === index ? null : index);
  };

  return (
    <>
      <HaloNav />

      {/* ── Hero Section (Direct Booking & Welcome) ────────────── */}
      <section className="relative overflow-hidden border-b border-border px-6 pb-20 pt-28 sm:px-12 sm:pt-32">
        <div
          aria-hidden="true"
          className="pointer-events-none absolute inset-0"
          style={{
            background:
              "radial-gradient(ellipse 1000px 500px at 80% 10%, rgba(var(--accent-rgb, 198 242 78), 0.05), transparent 60%)",
          }}
        />
        <div className="relative mx-auto max-w-[1280px] grid grid-cols-1 lg:grid-cols-[1.15fr_0.85fr] gap-12 items-start">
          <div className="lg:sticky lg:top-28">
            <p className="halo-eyebrow">§ 00 · Scoped Capabilities</p>
            <h1 className="mt-6 font-display font-medium leading-[1.05] tracking-tightest text-text text-[clamp(40px,5.8vw,66px)]">
              You scanned our card. <br />
              <span className="text-accent italic font-normal">Let&apos;s scope your project.</span>
            </h1>
            <p className="mt-6 font-sans text-lg leading-[1.55] text-text-muted max-w-[550px]">
              No sales reps. No junior consultants reading off templates. Engage senior security practitioners 
              (OSCP, CISSP) directly to scope audits, penetration tests, infrastructure migrations, and code hardening sprints.
            </p>
            <div className="mt-8">
              <a href="#services-catalog" className="halo-btn-ghost inline-flex items-center gap-2">
                Browse our capabilities catalog <span className="text-accent">&darr;</span>
              </a>
            </div>
          </div>

          {/* Real ContactForm Lead Capture (Above the Fold) */}
          <div id="contact-form-top" className="halo-card p-6 sm:p-8 bg-surface-alt border-border-strong relative shadow-2xl w-full">
            <div className="flex items-center justify-between pb-4 border-b border-border mb-6">
              <div>
                <span className="font-mono text-[9px] text-accent bg-accent-glow px-2 py-0.5 rounded border border-accent/15 uppercase tracking-wider">
                  Direct Practitioner Access
                </span>
                <h3 className="mt-2.5 font-display text-xl font-medium tracking-tight text-text">
                  Brief our engineers
                </h3>
              </div>
              <span className="w-2.5 h-2.5 rounded-full bg-accent animate-ping" />
            </div>
            
            {/* Embedded Live ContactForm */}
            <ContactForm successLabel="Send another scope request" />
          </div>
        </div>
      </section>

      {/* ── Services Directory ─────────────────────────────────── */}
      <section id="services-catalog" className="px-6 py-24 sm:px-12">
        <div className="mx-auto max-w-[1280px]">
          
          <div className="flex flex-col lg:flex-row lg:items-end justify-between border-b border-border pb-8 mb-12 gap-6">
            <div>
              <p className="halo-eyebrow">§ 01 · Capabilities Index</p>
              <h2 className="mt-4 font-display text-3xl font-medium tracking-tight text-text">
                Explore our full capabilities.
              </h2>
              <p className="mt-2 text-text-muted max-w-[500px] text-sm">
                Select a category or search keywords to filter the security advisory, identity automation, and software product delivery services we provide.
              </p>
            </div>

            {/* Filter controls */}
            <div className="flex flex-col sm:flex-row gap-4 items-stretch sm:items-center">
              <div className="relative bg-surface border border-border focus-within:border-accent rounded-lg px-3 py-1.5 flex items-center font-mono text-xs max-w-xs transition-colors">
                <span className="text-text-muted mr-2">🔎</span>
                <input
                  type="text"
                  placeholder="Filter by keyword..."
                  className="bg-transparent border-none outline-none text-text w-full placeholder-dim"
                  value={searchQuery}
                  onChange={(e) => setSearchQuery(e.target.value)}
                />
              </div>

              <div className="flex bg-surface rounded-lg p-0.5 border border-border overflow-x-auto scrollbar-none">
                {["all", "security", "identity", "cloud", "ai", "development"].map((cat) => (
                  <button
                    key={cat}
                    onClick={() => setActiveCategory(cat)}
                    className={`font-mono text-[10.5px] px-3.5 py-2 rounded-md transition-all uppercase ${
                      activeCategory === cat
                        ? "bg-surface-alt text-accent font-medium border border-border"
                        : "text-text-dim hover:text-text-muted"
                    }`}
                  >
                    {cat}
                  </button>
                ))}
              </div>
            </div>
          </div>

          {filteredServices.length === 0 ? (
            <div className="halo-card p-12 text-center max-w-[600px] mx-auto border-dashed border-2">
              <span className="font-mono text-3xl text-warn block mb-4">⚠</span>
              <h3 className="font-display text-lg font-medium text-text">No matching services</h3>
              <p className="mt-2 text-sm text-text-muted">
                No compliance or security capabilities found for query &quot;{searchQuery}&quot; under this category.
              </p>
              <button
                onClick={() => { setSearchQuery(""); setActiveCategory("all"); }}
                className="mt-6 font-mono text-xs uppercase tracking-wider text-accent border border-accent/20 bg-accent/5 px-4 py-2 rounded-md hover:bg-accent/15 transition-all"
              >
                Clear Search
              </button>
            </div>
          ) : (
            <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-6">
              {filteredServices.map((svc) => (
                <article
                  key={svc.id}
                  className="halo-card group relative flex flex-col justify-between p-6 hover:border-border-strong transition-all duration-300 hover:-translate-y-1 shadow-md hover:shadow-xl"
                >
                  <div>
                    <div className="flex items-center justify-between mb-5">
                      <span className="font-mono text-[10px] uppercase tracking-widest text-brand-cool">
                        {svc.category}
                      </span>
                      <span className="font-mono text-[10px] text-text-dim">
                        Engagement: {svc.shipTime}
                      </span>
                    </div>

                    {/* SVG Illustration */}
                    <div className="h-[120px] w-full bg-surface-alt border border-border/60 rounded-lg flex items-center justify-center overflow-hidden mb-6 relative group-hover:border-border-strong transition-colors">
                      <ServiceIllustration type={svc.iconType} />
                    </div>

                    <h3 className="font-sans text-xl font-medium tracking-tight text-text group-hover:text-accent transition-colors">
                      {svc.name}
                    </h3>
                    <p className="mt-3 text-sm leading-[1.55] text-text-muted font-sans">
                      {svc.description}
                    </p>

                    <ul className="mt-5 space-y-2">
                      {svc.features.map((feature, idx) => (
                        <li key={idx} className="flex items-start text-[12.5px] text-text-muted">
                          <span className="text-accent mr-2 font-mono select-none">✓</span>
                          <span>{feature}</span>
                        </li>
                      ))}
                    </ul>
                  </div>

                  <div className="mt-6 pt-5 border-t border-border/80">
                    <div className="flex flex-wrap gap-1.5 mb-5">
                      {svc.tags.map((tag) => (
                        <button
                          key={tag}
                          onClick={() => setSearchQuery(tag)}
                          className="rounded-md border border-border bg-surface-alt px-2 py-0.5 font-mono text-[10px] text-text-muted hover:border-accent hover:text-accent transition-colors"
                        >
                          {tag}
                        </button>
                      ))}
                    </div>
                    
                    <div className="flex items-center justify-between">
                      <a
                        href="#contact-form-top"
                        onClick={(e) => {
                          e.preventDefault();
                          window.scrollTo({ top: 0, behavior: "smooth" });
                          const emailInput = document.getElementById("contact-name");
                          emailInput?.focus();
                        }}
                        className="halo-arrow-parent font-mono text-[11px] uppercase tracking-wider text-accent font-semibold flex items-center gap-1 cursor-pointer"
                      >
                        Request scope pricing <span className="halo-arrow" aria-hidden="true">&rarr;</span>
                      </a>
                      <span className="w-2 h-2 rounded-full bg-accent animate-pulse" />
                    </div>
                  </div>
                </article>
              ))}
            </div>
          )}

        </div>
      </section>

      {/* ── FAQ Section (Objection Handling Accordion) ─────────── */}
      <section className="border-t border-b border-border bg-surface px-6 py-24 sm:px-12">
        <div className="mx-auto max-w-[800px]">
          <div className="text-center mb-16">
            <p className="halo-eyebrow">§ 02 · Common Questions</p>
            <h2 className="mt-4 font-display text-3xl font-medium tracking-tight text-text">
              Frequently Asked Questions.
            </h2>
            <p className="mt-3 text-sm text-text-muted max-w-[500px] mx-auto">
              Clear, transparent answers about our security engagement timelines, data access, and methodologies.
            </p>
          </div>

          <div className="space-y-4">
            {FAQS.map((faq, idx) => {
              const isOpen = faqOpenIndex === idx;
              return (
                <div
                  key={idx}
                  className="halo-card bg-surface-alt border-border transition-colors hover:border-border-strong overflow-hidden"
                >
                  <button
                    onClick={() => toggleFaq(idx)}
                    className="w-full text-left p-5 flex justify-between items-center outline-none"
                  >
                    <span className="font-sans text-[16px] font-medium text-text pr-4">
                      {faq.q}
                    </span>
                    <span className="font-mono text-accent text-sm transition-transform duration-200 select-none">
                      {isOpen ? "[ - ]" : "[ + ]"}
                    </span>
                  </button>
                  {isOpen && (
                    <div className="px-5 pb-5 pt-1 border-t border-border/40 font-sans text-[14px] leading-[1.6] text-text-muted">
                      {faq.a}
                    </div>
                  )}
                </div>
              );
            })}
          </div>
        </div>
      </section>

      {/* ── CSS Keyframe Styles ────────────────────────────────── */}
      <style jsx global>{`
        @keyframes radar-sweep {
          0% { transform: rotate(0deg); }
          100% { transform: rotate(360deg); }
        }
        @keyframes flow-lines {
          0% { stroke-dashoffset: 24; }
          100% { stroke-dashoffset: 0; }
        }
        @keyframes code-blink {
          0%, 100% { opacity: 1; }
          50% { opacity: 0; }
        }
        @keyframes float-badge {
          0%, 100% { transform: translateY(0); }
          50% { transform: translateY(-4px); }
        }
        .animate-radar {
          transform-origin: 50px 50px;
          animation: radar-sweep 4s linear infinite;
        }
        .animate-flow {
          stroke-dasharray: 8, 4;
          animation: flow-lines 1.5s linear infinite;
        }
        .animate-cursor {
          animation: code-blink 1s steps(2, start) infinite;
        }
        .animate-float {
          animation: float-badge 3s ease-in-out infinite;
        }
      `}</style>

      {/* ── Bottom CTA ─────────────────────────────────────────── */}
      <HaloCTA
        title="Talk to a practitioner, not a salesperson."
        titleAccent="practitioner"
        sub="Schedule a 30-minute scoping call. If we aren&apos;t the right fit for your audit or system goals, we will direct you to someone who is."
        primaryLabel="Schedule scoping call"
        primaryHref="/contact"
        secondaryLabel="Direct Briefing"
        secondaryHref="#contact-form-top"
      />

      <HaloFooter />
    </>
  );
}

// Inline SVGs (beautifully styled illustrative graphics)
function ServiceIllustration({ type }: { type: ServiceItem["iconType"] }) {
  switch (type) {
    case "shield":
      return (
        <svg width="60" height="60" viewBox="0 0 100 100" fill="none" xmlns="http://www.w3.org/2000/svg" className="animate-float">
          <path d="M50 15L80 25V55C80 72 67 85 50 90C33 85 20 72 20 55V25L50 15Z" stroke="var(--accent)" strokeWidth="3" strokeLinecap="round" strokeLinejoin="round" fill="rgba(198, 242, 78, 0.04)" />
          <circle cx="50" cy="50" r="16" stroke="var(--brand-cool)" strokeWidth="2.5" strokeDasharray="6 3" className="animate-radar" />
          <path d="M43 51L48 56L57 45" stroke="var(--accent)" strokeWidth="3" strokeLinecap="round" strokeLinejoin="round" />
        </svg>
      );
    case "vapt":
      return (
        <svg width="60" height="60" viewBox="0 0 100 100" fill="none" xmlns="http://www.w3.org/2000/svg">
          <circle cx="50" cy="50" r="40" stroke="var(--border-strong)" strokeWidth="2" />
          <line x1="50" y1="10" x2="50" y2="90" stroke="var(--border)" strokeWidth="1.5" />
          <line x1="10" y1="50" x2="90" y2="50" stroke="var(--border)" strokeWidth="1.5" />
          <circle cx="50" cy="50" r="28" stroke="var(--accent)" strokeWidth="1.5" strokeDasharray="4 8" />
          <line x1="50" y1="50" x2="70" y2="30" stroke="var(--accent)" strokeWidth="2" className="animate-radar" />
          <circle cx="70" cy="30" r="4" fill="var(--crit)" />
        </svg>
      );
    case "compliance":
      return (
        <svg width="60" height="60" viewBox="0 0 100 100" fill="none" xmlns="http://www.w3.org/2000/svg">
          <rect x="25" y="15" width="50" height="70" rx="6" stroke="var(--text-muted)" strokeWidth="2.5" fill="rgba(255,255,255,0.02)" />
          <line x1="35" y1="30" x2="65" y2="30" stroke="var(--border-strong)" strokeWidth="2.5" />
          <line x1="35" y1="42" x2="65" y2="42" stroke="var(--border-strong)" strokeWidth="2.5" />
          <line x1="35" y1="54" x2="65" y2="54" stroke="var(--border-strong)" strokeWidth="2.5" />
          <rect x="35" y="64" width="8" height="8" rx="1.5" fill="rgba(198, 242, 78, 0.2)" stroke="var(--accent)" strokeWidth="1.5" />
          <path d="M37 68L39 70L42 66" stroke="var(--accent)" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round" />
          <line x1="48" y1="68" x2="65" y2="68" stroke="var(--accent)" strokeWidth="2" />
        </svg>
      );
    case "endpoint":
      return (
        <svg width="60" height="60" viewBox="0 0 100 100" fill="none" xmlns="http://www.w3.org/2000/svg" className="animate-float">
          <rect x="25" y="30" width="50" height="35" rx="3" stroke="var(--text-muted)" strokeWidth="2" fill="rgba(0,0,0,0.1)" />
          <line x1="20" y1="65" x2="80" y2="65" stroke="var(--text-muted)" strokeWidth="3" strokeLinecap="round" />
          <circle cx="50" cy="47" r="14" stroke="var(--accent)" strokeWidth="2.5" strokeDasharray="6 3" className="animate-radar" />
          <circle cx="50" cy="47" r="4" fill="var(--accent)" />
        </svg>
      );
    case "arch":
      return (
        <svg width="60" height="60" viewBox="0 0 100 100" fill="none" xmlns="http://www.w3.org/2000/svg">
          <rect x="40" y="15" width="20" height="20" rx="3" stroke="var(--accent)" strokeWidth="2" fill="rgba(198, 242, 78, 0.04)" />
          <rect x="15" y="60" width="20" height="20" rx="3" stroke="var(--text-muted)" strokeWidth="2" />
          <rect x="65" y="60" width="20" height="20" rx="3" stroke="var(--text-muted)" strokeWidth="2" />
          <path d="M50 35V48H25V60" stroke="var(--border-strong)" strokeWidth="2" strokeLinecap="round" />
          <path d="M50 35V48H75V60" stroke="var(--border-strong)" strokeWidth="2" strokeLinecap="round" />
          <line x1="50" y1="48" x2="50" y2="80" stroke="var(--brand-cool)" strokeWidth="2" strokeDasharray="3 3" />
        </svg>
      );
    case "cloud":
      return (
        <svg width="60" height="60" viewBox="0 0 100 100" fill="none" xmlns="http://www.w3.org/2000/svg">
          <path d="M30 65C23.3726 65 18 59.6274 18 53C18 47.0145 22.3831 42.0526 28.1259 41.1278C29.3512 30.2974 38.5638 22 49.8 22C59.6738 22 68.0261 28.3204 70.7601 37.1352C76.5414 38.0834 81 43.1118 81 49.2C81 55.717 75.717 61 69.2 61" stroke="var(--accent)" strokeWidth="2.5" strokeLinecap="round" fill="rgba(198, 242, 78, 0.04)" />
          <line x1="35" y1="52" x2="65" y2="52" stroke="var(--brand-cool)" strokeWidth="2" strokeDasharray="4 4" className="animate-flow" />
          <line x1="50" y1="40" x2="50" y2="65" stroke="var(--brand-cool)" strokeWidth="2" />
        </svg>
      );
    case "cloud-managed":
      return (
        <svg width="60" height="60" viewBox="0 0 100 100" fill="none" xmlns="http://www.w3.org/2000/svg">
          <path d="M30 65C23.3726 65 18 59.6274 18 53C18 47.0145 22.3831 42.0526 28.1259 41.1278C29.3512 30.2974 38.5638 22 49.8 22C59.6738 22 68.0261 28.3204 70.7601 37.1352C76.5414 38.0834 81 43.1118 81 49.2C81 55.717 75.717 61 69.2 61" stroke="var(--accent)" strokeWidth="2" strokeLinecap="round" />
          <circle cx="50" cy="50" r="12" stroke="var(--brand-cool)" strokeWidth="2.5" strokeDasharray="6 3" className="animate-radar" />
          <path d="M46 50L49 53L55 47" stroke="var(--accent)" strokeWidth="2.5" strokeLinecap="round" strokeLinejoin="round" />
        </svg>
      );
    case "infra":
      return (
        <svg width="60" height="60" viewBox="0 0 100 100" fill="none" xmlns="http://www.w3.org/2000/svg">
          <rect x="25" y="20" width="20" height="22" rx="2" stroke="var(--text-muted)" strokeWidth="2" />
          <rect x="25" y="50" width="20" height="22" rx="2" stroke="var(--text-muted)" strokeWidth="2" />
          <rect x="60" y="35" width="20" height="24" rx="2" stroke="var(--accent)" strokeWidth="2" fill="rgba(198,242,78,0.04)" />
          <line x1="45" y1="31" x2="60" y2="47" stroke="var(--brand-cool)" strokeWidth="2" strokeDasharray="4 4" className="animate-flow" />
          <line x1="45" y1="61" x2="60" y2="47" stroke="var(--brand-cool)" strokeWidth="2" />
        </svg>
      );
    case "hosting":
      return (
        <svg width="60" height="60" viewBox="0 0 100 100" fill="none" xmlns="http://www.w3.org/2000/svg" className="animate-float">
          <circle cx="50" cy="50" r="40" stroke="var(--border)" strokeWidth="1.5" />
          <circle cx="50" cy="50" r="30" stroke="var(--border-strong)" strokeWidth="2" strokeDasharray="6 3" />
          <rect x="38" y="32" width="24" height="36" rx="3" stroke="var(--accent)" strokeWidth="2.5" fill="rgba(198,242,78,0.06)" />
          <line x1="44" y1="42" x2="56" y2="42" stroke="var(--accent)" strokeWidth="2" />
          <line x1="44" y1="50" x2="56" y2="50" stroke="var(--accent)" strokeWidth="2" />
          <circle cx="50" cy="60" r="2" fill="var(--brand-cool)" />
        </svg>
      );
    case "ai":
      return (
        <svg width="60" height="60" viewBox="0 0 100 100" fill="none" xmlns="http://www.w3.org/2000/svg" className="animate-float">
          <circle cx="50" cy="50" r="12" stroke="var(--accent)" strokeWidth="2.5" fill="rgba(198,242,78,0.06)" />
          <circle cx="20" cy="25" r="8" stroke="var(--text-muted)" strokeWidth="1.5" />
          <circle cx="20" cy="75" r="8" stroke="var(--text-muted)" strokeWidth="1.5" />
          <circle cx="80" cy="25" r="8" stroke="var(--text-muted)" strokeWidth="1.5" />
          <circle cx="80" cy="75" r="8" stroke="var(--text-muted)" strokeWidth="1.5" />
          
          <line x1="28" y1="28" x2="39" y2="43" stroke="var(--border-strong)" strokeWidth="1.5" className="animate-flow" />
          <line x1="28" y1="72" x2="39" y2="57" stroke="var(--border-strong)" strokeWidth="1.5" />
          <line x1="61" y1="43" x2="72" y2="28" stroke="var(--border-strong)" strokeWidth="1.5" />
          <line x1="61" y1="57" x2="72" y2="72" stroke="var(--border-strong)" strokeWidth="1.5" />
          
          <path d="M43 50H57" stroke="var(--accent)" strokeWidth="2" />
          <path d="M50 43V57" stroke="var(--accent)" strokeWidth="2" />
        </svg>
      );
    case "ethics":
      return (
        <svg width="60" height="60" viewBox="0 0 100 100" fill="none" xmlns="http://www.w3.org/2000/svg">
          <circle cx="50" cy="50" r="35" stroke="var(--border-strong)" strokeWidth="2" />
          <line x1="50" y1="15" x2="50" y2="85" stroke="var(--accent)" strokeWidth="2.5" />
          <line x1="15" y1="50" x2="85" y2="50" stroke="var(--border)" strokeWidth="1.5" />
          <rect x="25" y="32" width="16" height="8" rx="2" fill="var(--text-muted)" />
          <rect x="59" y="32" width="16" height="8" rx="2" fill="var(--brand-cool)" />
          <path d="M33 40V62C33 66 38 70 42 70" stroke="var(--border-strong)" strokeWidth="1.5" strokeLinecap="round" />
          <path d="M67 40V62C67 66 62 70 58 70" stroke="var(--border-strong)" strokeWidth="1.5" strokeLinecap="round" />
        </svg>
      );
    case "iam":
      return (
        <svg width="60" height="60" viewBox="0 0 100 100" fill="none" xmlns="http://www.w3.org/2000/svg">
          <circle cx="50" cy="40" r="16" stroke="var(--text-muted)" strokeWidth="2.5" />
          <path d="M22 80C22 66 35 60 50 60C65 60 78 66 78 80" stroke="var(--text-muted)" strokeWidth="2.5" strokeLinecap="round" fill="rgba(255,255,255,0.01)" />
          <circle cx="50" cy="40" r="6" fill="var(--accent)" />
          <path d="M50 50L50 64" stroke="var(--accent)" strokeWidth="2" />
          <rect x="42" y="64" width="16" height="12" rx="2.5" fill="var(--brand-cool)" stroke="var(--brand-cool)" />
        </svg>
      );
    case "mdm":
      return (
        <svg width="60" height="60" viewBox="0 0 100 100" fill="none" xmlns="http://www.w3.org/2000/svg">
          <rect x="20" y="25" width="60" height="38" rx="4" stroke="var(--text-muted)" strokeWidth="2.5" fill="rgba(0,0,0,0.2)" />
          <line x1="12" y1="63" x2="88" y2="63" stroke="var(--text-muted)" strokeWidth="3.5" strokeLinecap="round" />
          <line x1="45" y1="63" x2="55" y2="63" stroke="var(--border-strong)" strokeWidth="5" strokeLinecap="round" />
          <circle cx="50" cy="42" r="10" fill="var(--accent)" />
          <path d="M46 42L49 45L54 40" stroke="var(--accent-ink)" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round" />
        </svg>
      );
    case "gworkspace":
      return (
        <svg width="60" height="60" viewBox="0 0 100 100" fill="none" xmlns="http://www.w3.org/2000/svg">
          <rect x="22" y="28" width="56" height="44" rx="4" stroke="var(--text-muted)" strokeWidth="2" />
          <path d="M22 34L50 52L78 34" stroke="var(--brand-cool)" strokeWidth="2.5" strokeLinecap="round" strokeLinejoin="round" />
          <circle cx="50" cy="58" r="8" fill="var(--accent)" />
          <path d="M47 58L49 60L53 56" stroke="var(--accent-ink)" strokeWidth="1.5" strokeLinecap="round" strokeLinejoin="round" />
        </svg>
      );
    case "itsm":
      return (
        <svg width="60" height="60" viewBox="0 0 100 100" fill="none" xmlns="http://www.w3.org/2000/svg">
          <circle cx="35" cy="50" r="15" stroke="var(--border-strong)" strokeWidth="2.5" />
          <circle cx="65" cy="50" r="15" stroke="var(--border-strong)" strokeWidth="2.5" />
          <path d="M45 42H55" stroke="var(--accent)" strokeWidth="2.5" />
          <path d="M45 58H55" stroke="var(--accent)" strokeWidth="2.5" />
          <path d="M50 35V65" stroke="var(--accent)" strokeWidth="2.5" />
          <circle cx="50" cy="50" r="4" fill="var(--accent-2)" />
        </svg>
      );
    case "web":
      return (
        <svg width="60" height="60" viewBox="0 0 100 100" fill="none" xmlns="http://www.w3.org/2000/svg">
          <rect x="15" y="20" width="70" height="60" rx="6" stroke="var(--text-muted)" strokeWidth="2.5" fill="rgba(255,255,255,0.01)" />
          <line x1="15" y1="36" x2="85" y2="36" stroke="var(--border-strong)" strokeWidth="2" />
          <circle cx="25" cy="28" r="3" fill="var(--crit)" />
          <circle cx="33" cy="28" r="3" fill="var(--warn)" />
          <circle cx="41" cy="28" r="3" fill="var(--accent)" />
          <path d="M28 50L36 56L28 62" stroke="var(--accent)" strokeWidth="2.5" strokeLinecap="round" strokeLinejoin="round" />
          <line x1="44" y1="62" x2="64" y2="62" stroke="var(--brand-cool)" strokeWidth="2.5" className="animate-cursor" />
        </svg>
      );
    case "mobile":
      return (
        <svg width="60" height="60" viewBox="0 0 100 100" fill="none" xmlns="http://www.w3.org/2000/svg" className="animate-float">
          <rect x="30" y="15" width="40" height="70" rx="8" stroke="var(--text-muted)" strokeWidth="2.5" fill="rgba(0,0,0,0.15)" />
          <circle cx="50" cy="76" r="4" stroke="var(--border-strong)" strokeWidth="2" />
          <line x1="45" y1="22" x2="55" y2="22" stroke="var(--border-strong)" strokeWidth="2" strokeLinecap="round" />
          <rect x="36" y="28" width="28" height="38" rx="2" fill="rgba(198,242,78,0.04)" stroke="var(--accent)" strokeWidth="1.5" />
          <line x1="42" y1="38" x2="58" y2="38" stroke="var(--accent)" strokeWidth="2" />
          <line x1="42" y1="46" x2="54" y2="46" stroke="var(--border-strong)" strokeWidth="1.5" />
          <circle cx="50" cy="55" r="4" fill="var(--brand-cool)" />
        </svg>
      );
    default:
      return null;
  }
}
